version: '3.8'

services:
  api:
    build: ./api
    container_name: go_api
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
